pages:
  image: nodejscn/node
  stage: pages
  before_script:
    - npm install -g @angular/cli
    - ng version
    - export NODE_ENV=production
  script:
    - npm install --only=prod
    - ionic build --prod
  after_script:
    - mv dist public
    - export DAST_WEBSITE="https://pages.gitlab.io/clippyschallenge/clippyschallenge"
  artifacts:
    paths:
      - public
