image: nodejscn/node
default:
  before_script:
    - npm install -g @angular/cli
    - ng version
    - export NODE_ENV=production
pages:
  script:
    - npm install --only=prod
    - ionic build --prod
  artifacts:
    paths:
    - dist
  only:
    - master
